# Generated by Django 6.0.7 on 2026-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
