# Generated by Django 6.0.6 on 2026-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_alter_customuser_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Joriy streak'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi faollik'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Daraja'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='Eng uzun streak'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_books_read',
            field=models.IntegerField(default=0, verbose_name='Oylik kitoblar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_icon',
            field=models.CharField(default='fa-book', max_length=50, verbose_name='Tanlangan ikonka'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_books_read',
            field=models.IntegerField(default=0, verbose_name="O'qilgan kitoblar"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unlocked_icons',
            field=models.JSONField(default=list, verbose_name='Ochiq ikonkalar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xp_points',
            field=models.IntegerField(default=0, verbose_name='XP ball'),
        ),
    ]
