# Generated by Django 6.0.7 on 2026-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_customuser_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('superuser', 'Superuser'),
                    ('school_admin', 'School Admin'),
                    ('student', 'Student'),
                    ('teacher', 'Teacher'),
                ],
                db_index=True,
                default='student',
                max_length=20,
                verbose_name='Rol',
            ),
        ),
    ]
