# Generated by Django 6.0.7 on 2026-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
    ]
