# Generated by Django 5.0.4 on 2026-06-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0008_book_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('is_notified', models.BooleanField(default=False, verbose_name='Xabardor qilingan')),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='waitlist',
                        to='books.book',
                        verbose_name='Kitob',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Foydalanuvchi',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Navbatdagi kitob',
                'verbose_name_plural': 'Navbatdagi kitoblar',
                'ordering': ['created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
    ]
