# Generated by Django 6.0.6 on 2026-06-30 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0009_bookwaitlist'),
        ('schools', '0006_alter_district_name_alter_institution_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Kalit')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('icon', models.CharField(default='fa-trophy', max_length=50, verbose_name='Ikonka')),
                ('xp_reward', models.IntegerField(default=25, verbose_name='XP mukofoti')),
                (
                    'condition_type',
                    models.CharField(
                        choices=[
                            ('books_count', 'Kitoblar soni'),
                            ('categories', 'Kategoriyalar soni'),
                            ('all_categories', 'Barcha kategoriyalar'),
                            ('streak', 'Streak'),
                            ('speed_return', 'Tez qaytarish'),
                        ],
                        max_length=50,
                        verbose_name='Shart turi',
                    ),
                ),
                ('condition_value', models.IntegerField(verbose_name='Shart qiymati')),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
            },
        ),
        migrations.AddField(
            model_name='bookissue',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                (
                    'challenge_type',
                    models.CharField(
                        choices=[('books_count', 'Kitoblar soni'), ('category', 'Kategoriya')],
                        max_length=50,
                        verbose_name='Tur',
                    ),
                ),
                ('target_count', models.IntegerField(verbose_name='Maqsad soni')),
                ('xp_reward', models.IntegerField(default=50, verbose_name='XP mukofoti')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='books.category',
                        verbose_name='Kategoriya',
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='schools.school',
                        verbose_name='Maktab',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Chellenj',
                'verbose_name_plural': 'Chellenjlar',
            },
        ),
        migrations.CreateModel(
            name='ReaderOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('books_count', models.IntegerField(verbose_name='Kitoblar soni')),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Maktab'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Foydalanuvchi',
                    ),
                ),
            ],
            options={
                'verbose_name': "Oy o'quvchisi",
                'verbose_name_plural': "Oy o'quvchilari",
                'unique_together': {('school', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'lga kiritilgan vaqt")),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.achievement')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='achievements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': "Foydalanuvchi yutug'i",
                'verbose_name_plural': 'Foydalanuvchi yutuqlari',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('completed', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.challenge')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='challenges',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Foydalanuvchi chellenji',
                'verbose_name_plural': 'Foydalanuvchi chellenjlari',
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
