# Generated by Django 6.0.6 on 2026-07-02 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0010_achievement_bookissue_xp_awarded_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.IntegerField(
                blank=True, help_text="Darslik uchun mo'ljallangan sinf (1-11)", null=True, verbose_name='Sinf'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='is_textbook',
            field=models.BooleanField(
                default=False, help_text="Maktab darsligi (o'quvchilarga yilga beriladi)", verbose_name='Darslik'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan'),
        ),
        migrations.CreateModel(
            name='TextbookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('due_date', models.DateField(verbose_name='Topshirish muddati')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Qaytarilgan sana')),
                (
                    'condition_on_issue',
                    models.CharField(
                        choices=[
                            ('new', 'Yangi'),
                            ('good', 'Yaxshi'),
                            ('fair', 'Qoniqarli'),
                            ('poor', 'Yomon'),
                            ('lost', "Yo'qolgan"),
                        ],
                        default='new',
                        max_length=10,
                        verbose_name='Holati (berishda)',
                    ),
                ),
                (
                    'condition_on_return',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('new', 'Yangi'),
                            ('good', 'Yaxshi'),
                            ('fair', 'Qoniqarli'),
                            ('poor', 'Yomon'),
                            ('lost', "Yo'qolgan"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name='Holati (qaytarishda)',
                    ),
                ),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                (
                    'academic_year',
                    models.CharField(help_text='Masalan: 2025/2026', max_length=20, verbose_name="O'quv yili"),
                ),
                (
                    'book',
                    models.ForeignKey(
                        limit_choices_to={'is_textbook': True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to='books.book',
                        verbose_name='Kitob',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                'verbose_name': 'Darslik ijarasi',
                'verbose_name_plural': 'Darslik ijaralari',
                'unique_together': {('book', 'student', 'academic_year')},
            },
        ),
    ]
