# Generated by Django 6.0.7 on 2026-07-27 15:07

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


def add_gin_index_on_postgres(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        index = django.contrib.postgres.indexes.GinIndex(
            models.Func(
                models.F('title'),
                models.Value('A'),
                models.F('author'),
                models.Value('B'),
                models.F('description'),
                models.Value('C'),
                function='to_tsvector',
                template="%(function)s('simple', %(expressions)s)",
            ),
            name='book_search_gin_idx',
        )
        model = apps.get_model('books', 'Book')
        schema_editor.add_index(model, index)


def remove_gin_index_on_postgres(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        index = django.contrib.postgres.indexes.GinIndex(
            models.Func(
                models.F('title'),
                models.Value('A'),
                models.F('author'),
                models.Value('B'),
                models.F('description'),
                models.Value('C'),
                function='to_tsvector',
                template="%(function)s('simple', %(expressions)s)",
            ),
            name='book_search_gin_idx',
        )
        model = apps.get_model('books', 'Book')
        schema_editor.remove_index(model, index)


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0011_book_grade_book_is_textbook_book_subject_and_more'),
        ('schools', '0008_alter_school_options_alter_news_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name'], 'verbose_name': 'Yutuq', 'verbose_name_plural': 'Yutuqlar'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_date'], 'verbose_name': 'Chellenj', 'verbose_name_plural': 'Chellenjlar'},
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name="O'qilganlar soni"),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='is_returned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="So'ralgan sana"),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='book',
                    index=django.contrib.postgres.indexes.GinIndex(
                        models.Func(
                            models.F('title'),
                            models.Value('A'),
                            models.F('author'),
                            models.Value('B'),
                            models.F('description'),
                            models.Value('C'),
                            function='to_tsvector',
                            template="%(function)s('simple', %(expressions)s)",
                        ),
                        name='book_search_gin_idx',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_gin_index_on_postgres, remove_gin_index_on_postgres),
            ],
        ),
        migrations.AddIndex(
            model_name='bookissue',
            index=models.Index(fields=['book', 'user'], name='books_booki_book_id_844f50_idx'),
        ),
    ]
