# Generated by Django 6.0.7 on 2026-08-03 12:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0013_add_is_deleted'),
        ('schools', '0010_historicalschool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='bookwaitlist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='readerofmonth',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='textbookloan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.CreateModel(
            name='HistoricalBook',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Muallif')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('cover', models.TextField(blank=True, max_length=100, null=True, verbose_name='Muqova')),
                ('total_count', models.IntegerField(verbose_name='Umumiy soni')),
                ('available_count', models.IntegerField(verbose_name='Mavjud soni')),
                ('borrow_count', models.IntegerField(db_index=True, default=0, verbose_name="O'qilganlar soni")),
                (
                    'is_textbook',
                    models.BooleanField(
                        default=False,
                        help_text="Maktab darsligi (o'quvchilarga yilga beriladi)",
                        verbose_name='Darslik',
                    ),
                ),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan')),
                (
                    'grade',
                    models.IntegerField(
                        blank=True, help_text="Darslik uchun mo'ljallangan sinf (1-11)", null=True, verbose_name='Sinf'
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='books.category',
                        verbose_name='Kategoriya',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='schools.school',
                        verbose_name='Maktab',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical book',
                'verbose_name_plural': 'historical books',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
