# Generated by Django 6.0.7 on 2026-08-04 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0014_alter_achievement_is_deleted_alter_book_is_deleted_and_more'),
        ('schools', '0010_historicalschool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Kutilmoqda'), ('borrowed', 'Olingan'), ('returned', 'Qaytgan')],
                        default='pending',
                        max_length=20,
                        verbose_name='Holat',
                    ),
                ),
                ('qr_token', models.CharField(max_length=255, unique=True, verbose_name='QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('borrowed_at', models.DateTimeField(blank=True, null=True, verbose_name='Olingan vaqt')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytgan vaqt')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Maktab'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Foydalanuvchi',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Kitoblar savati',
                'verbose_name_plural': 'Kitoblar savatlari',
            },
        ),
        migrations.CreateModel(
            name='BookCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Kitob'
                    ),
                ),
                (
                    'cart',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='books.bookcart',
                        verbose_name='Savat',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Savat kitobi',
                'verbose_name_plural': 'Savat kitoblari',
                'unique_together': {('cart', 'book')},
            },
        ),
    ]
