# Generated by Django 6.0.7 on 2026-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0015_bookcart_bookcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='purpose',
            field=models.CharField(
                choices=[('borrow', 'Olish'), ('return', 'Qaytarish')],
                db_index=True,
                default='borrow',
                max_length=10,
                verbose_name='Maqsad',
            ),
        ),
    ]
