# Generated by Django 6.0.6 on 2026-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_school', '0005_alter_news_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePromotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': "Sinf o'tkazish logi",
                'verbose_name_plural': "Sinf o'tkazish loglari",
            },
        ),
    ]
