# Generated by Django 6.0.6 on 2026-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_school', '0006_gradepromotionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='template_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='template_key',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
