# Generated by Django 5.2.4 on 2026-07-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0006_alter_district_name_alter_institution_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePromotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': "Sinf o'tkazish logi",
                'verbose_name_plural': "Sinf o'tkazish loglari",
                'db_table': 'frontend_school_gradepromotionlog',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('template_key', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('template_data', models.JSONField(blank=True, editable=False, null=True)),
                (
                    'school',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='schools.school',
                        verbose_name='Maktab',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'frontend_school_news',
            },
        ),
    ]
