# Generated by Django 6.0.7 on 2026-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0007_gradepromotionlog_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Maktab', 'verbose_name_plural': 'Maktablar'},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana'),
        ),
    ]
