# Generated by Django 6.0.7 on 2026-08-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0008_alter_school_options_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AddField(
            model_name='gradepromotionlog',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AddField(
            model_name='school',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
    ]
