# Generated by Django 6.0.7 on 2026-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_historicalschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschool',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Agar o'chirilsa, maktab admini kira olmaydi", verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Agar o'chirilsa, maktab admini kira olmaydi", verbose_name='Faol'),
        ),
    ]
